spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: Hystrix
              args:
                name: account-service
                fallbackUri: forward:/fb/account

        - id: ticket-service
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/ticket/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: Hystrix
              args:
                name: ticket-service
                fallbackUri: forward:/fb/ticket


server:
  port: 8088

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    register-with-eureka: false
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

